// Writes docs/brand/logo-square.svg from docs/brand/logo.svg.
//
// `tauri icon` refuses a non-square source, so this centres the logo on a
// white square with a margin. The square is generated, never hand-edited, so
// the logo has one source.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const brandDir = fileURLToPath(new URL('../../../docs/brand/', import.meta.url))
const source = readFileSync(`${brandDir}logo.svg`, 'utf8')

// Read the logo's own frame rather than hard-coding it, so a new logo with
// different proportions needs no change here.
const rootTag = /<svg\b[^>]*viewBox="([-\d.]+) ([-\d.]+) ([\d.]+) ([\d.]+)"[^>]*>/
const match = rootTag.exec(source)
if (match === null) {
  throw new Error('logo.svg has no numeric viewBox on its root <svg>; cannot build the square icon')
}
const [minX, minY, width, height] = match.slice(1).map(Number)

// Room around the mark so launcher masks (circle, squircle) never clip it.
const MARGIN = Math.max(width, height) * 0.14
const round = (value) => Math.round(value * 100) / 100
const side = round(Math.max(width, height) + MARGIN * 2)
const x = round(minX - (side - width) / 2)
const y = round(minY - (side - height) / 2)

const square = source.replace(
  rootTag,
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${x} ${y} ${side} ${side}" width="1024" height="1024">\n` +
    `  <!-- GENERATED by apps/app/scripts/logo-square.mjs from logo.svg. Do not edit. -->\n` +
    `  <rect x="${x}" y="${y}" width="${side}" height="${side}" fill="#FFFFFF"/>`,
)

writeFileSync(`${brandDir}logo-square.svg`, square)
