// Writes docs/brand/logo-square.svg from docs/brand/logo.svg.
//
// `tauri icon` refuses a non-square source, so this builds the app icon: the
// monogram reversed to white (docs/brand.md: "reversed to white on green
// grounds") on a deep Rasko Green tile, the same ground as the app's sidebar.
// The tile is a rounded square inset on a transparent canvas, at Apple's icon
// grid proportions, because macOS draws icons exactly as supplied and a
// full-bleed square looks broken in the Dock. Windows and Android show the
// same tile. Generated, never hand-edited, so the logo has one source.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const brandDir = fileURLToPath(new URL('../../../docs/brand/', import.meta.url))
const source = readFileSync(`${brandDir}logo.svg`, 'utf8')

// Read the logo's own frame rather than hard-coding it, so a new logo with
// different proportions needs no change here.
const rootTag = /<svg\b[^>]*viewBox="([-\d.]+) ([-\d.]+) ([\d.]+) ([\d.]+)"[^>]*>/
const match = rootTag.exec(source)
if (match === null) {
  throw new Error('logo.svg has no numeric viewBox on its root <svg>; cannot build the square icon')
}
const [minX, minY, width, height] = match.slice(1).map(Number)

const TILE = '#16381A' // --rasko-green-active, the sidebar ground
/** Apple's grid: an 824-unit body on a 1024 canvas, corners at ~22.5% of the body. */
const BODY_SHARE = 824 / 1024
const CORNER_SHARE = 0.225
/** The mark's height as a share of the tile, so launcher masks never clip it. */
const MARK_SHARE = 0.62

const round = (value) => Math.round(value * 100) / 100
const body = round(height / MARK_SHARE)
const side = round(body / BODY_SHARE)
const x = round(minX - (side - width) / 2)
const y = round(minY - (side - height) / 2)
const bodyX = round(x + (side - body) / 2)
const bodyY = round(y + (side - body) / 2)

const square = source
  .replace(
    rootTag,
    // The logo's one colour lives on its root <svg>, which this replaces, so the
    // reversed white goes on the new root and every path inherits it.
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${x} ${y} ${side} ${side}" width="1024" height="1024" fill="#FFFFFF">\n` +
      `  <!-- GENERATED by apps/app/scripts/logo-square.mjs from logo.svg. Do not edit. -->\n` +
      `  <rect x="${bodyX}" y="${bodyY}" width="${body}" height="${body}" rx="${round(body * CORNER_SHARE)}" fill="${TILE}"/>`,
  )
  .replace(/fill="#134B21"/gi, 'fill="#FFFFFF"')

if (/fill="#134B21"/i.test(square)) {
  throw new Error('Could not reverse the logo to white; check its fill in logo.svg')
}

writeFileSync(`${brandDir}logo-square.svg`, square)
