// Writes docs/brand/logo-square.svg from docs/brand/logo.svg.
//
// `tauri icon` refuses a non-square source and the monogram is wide
// (3184 x 1664), so this centres it on a white square with a margin. The
// square is generated, never hand-edited, so the logo has one source.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const brandDir = fileURLToPath(new URL('../../../docs/brand/', import.meta.url))
const source = readFileSync(`${brandDir}logo.svg`, 'utf8')

const WIDTH = 3184
const HEIGHT = 1664
// Room around the mark so launcher masks (circle, squircle) never clip it.
const MARGIN = 400
const side = WIDTH + MARGIN * 2
const x = -MARGIN
const y = -(side - HEIGHT) / 2

const rootTag = /<svg\b[^>]*viewBox="0 0 3184 1664"[^>]*>/
if (!rootTag.test(source)) {
  throw new Error('logo.svg root <svg> no longer has viewBox "0 0 3184 1664"; update logo-square.mjs')
}

const square = source.replace(
  rootTag,
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${x} ${y} ${side} ${side}" width="1024" height="1024">\n` +
    `  <!-- GENERATED by apps/app/scripts/logo-square.mjs from logo.svg. Do not edit. -->\n` +
    `  <rect x="${x}" y="${y}" width="${side}" height="${side}" fill="#FFFFFF"/>`,
)

writeFileSync(`${brandDir}logo-square.svg`, square)
